[2024-02-01 13:13:16,266] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_10.dim_prov manual__2024-01-31T15:49:07.986872+00:00 [queued]>
[2024-02-01 13:13:16,281] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_10.dim_prov manual__2024-01-31T15:49:07.986872+00:00 [queued]>
[2024-02-01 13:13:16,282] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:13:16,282] {taskinstance.py:1357} INFO - Starting attempt 3 of 4
[2024-02-01 13:13:16,282] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 13:13:16,316] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_prov> on 2024-01-31 15:49:07.986872+00:00
[2024-02-01 13:13:16,334] {standard_task_runner.py:52} INFO - Started process 357 to run task
[2024-02-01 13:13:16,340] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_10', 'dim_prov', 'manual__2024-01-31T15:49:07.986872+00:00', '--job-id', '137', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpcvd82dye', '--error-file', '/tmp/tmpz51quk6t']
[2024-02-01 13:13:16,341] {standard_task_runner.py:80} INFO - Job 137: Subtask dim_prov
[2024-02-01 13:13:16,663] {task_command.py:369} INFO - Running <TaskInstance: project_6_10.dim_prov manual__2024-01-31T15:49:07.986872+00:00 [running]> on host 1fafaef2f352
[2024-02-01 13:13:16,966] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_10
AIRFLOW_CTX_TASK_ID=dim_prov
AIRFLOW_CTX_EXECUTION_DATE=2024-01-31T15:49:07.986872+00:00
AIRFLOW_CTX_TRY_NUMBER=3
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-01-31T15:49:07.986872+00:00
[2024-02-01 13:13:17,027] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-02-01 13:13:17,113] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS province_table (
    province_id SERIAL PRIMARY KEY,
    province_name VARCHAR(255) NOT NULL
);, parameters: None
[2024-02-01 13:13:17,126] {postgres.py:94} INFO - NOTICE:  relation "province_table" already exists, skipping

[2024-02-01 13:13:17,200] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_10, task_id=dim_prov, execution_date=20240131T154907, start_date=20240201T131316, end_date=20240201T131317
[2024-02-01 13:13:17,242] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 13:13:17,423] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
