[2024-02-01 16:30:10,321] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_21.dim_postgres manual__2024-02-01T16:28:51.921767+00:00 [queued]>
[2024-02-01 16:30:10,337] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_21.dim_postgres manual__2024-02-01T16:28:51.921767+00:00 [queued]>
[2024-02-01 16:30:10,338] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 16:30:10,338] {taskinstance.py:1357} INFO - Starting attempt 4 of 4
[2024-02-01 16:30:10,338] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 16:30:10,360] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_postgres> on 2024-02-01 16:28:51.921767+00:00
[2024-02-01 16:30:10,367] {standard_task_runner.py:52} INFO - Started process 7452 to run task
[2024-02-01 16:30:10,370] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_21', 'dim_postgres', 'manual__2024-02-01T16:28:51.921767+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpfhvf57dc', '--error-file', '/tmp/tmpwou53k9s']
[2024-02-01 16:30:10,371] {standard_task_runner.py:80} INFO - Job 334: Subtask dim_postgres
[2024-02-01 16:30:10,568] {task_command.py:369} INFO - Running <TaskInstance: project_6_21.dim_postgres manual__2024-02-01T16:28:51.921767+00:00 [running]> on host 1fafaef2f352
[2024-02-01 16:30:10,797] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_21
AIRFLOW_CTX_TASK_ID=dim_postgres
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T16:28:51.921767+00:00
AIRFLOW_CTX_TRY_NUMBER=4
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T16:28:51.921767+00:00
[2024-02-01 16:30:10,847] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-02-01 16:30:10,893] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS case_table (
    id INTEGER PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL,
    status_detail VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS province_table (
    province_id INTEGER PRIMARY KEY,
    province_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS district_table (
    district_id INTEGER PRIMARY KEY,
    province_id INTEGER REFERENCES province_table(province_id),
    district_name VARCHAR(255) NOT NULL
);
, parameters: None
[2024-02-01 16:30:10,905] {postgres.py:94} INFO - NOTICE:  relation "case_table" already exists, skipping

[2024-02-01 16:30:10,906] {postgres.py:94} INFO - NOTICE:  relation "province_table" already exists, skipping

[2024-02-01 16:30:10,906] {postgres.py:94} INFO - NOTICE:  relation "district_table" already exists, skipping

[2024-02-01 16:30:10,969] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_21, task_id=dim_postgres, execution_date=20240201T162851, start_date=20240201T163010, end_date=20240201T163010
[2024-02-01 16:30:11,003] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 16:30:11,141] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
