[2024-02-01 16:15:29,875] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_20.dim_postgres manual__2024-02-01T16:15:23.940128+00:00 [queued]>
[2024-02-01 16:15:29,899] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_20.dim_postgres manual__2024-02-01T16:15:23.940128+00:00 [queued]>
[2024-02-01 16:15:29,900] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 16:15:29,900] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-01 16:15:29,900] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 16:15:29,931] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_postgres> on 2024-02-01 16:15:23.940128+00:00
[2024-02-01 16:15:29,941] {standard_task_runner.py:52} INFO - Started process 6815 to run task
[2024-02-01 16:15:29,944] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_20', 'dim_postgres', 'manual__2024-02-01T16:15:23.940128+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp0por4fsq', '--error-file', '/tmp/tmpaby5nh72']
[2024-02-01 16:15:29,946] {standard_task_runner.py:80} INFO - Job 283: Subtask dim_postgres
[2024-02-01 16:15:30,166] {task_command.py:369} INFO - Running <TaskInstance: project_6_20.dim_postgres manual__2024-02-01T16:15:23.940128+00:00 [running]> on host 1fafaef2f352
[2024-02-01 16:15:30,521] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_20
AIRFLOW_CTX_TASK_ID=dim_postgres
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T16:15:23.940128+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T16:15:23.940128+00:00
[2024-02-01 16:15:30,617] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-02-01 16:15:30,685] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS case_table (
    id INTEGER PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL,
    status_detail VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS district_table (
    district_id INTEGER PRIMARY KEY,
    province_id INTEGER REFERENCES province_table(province_id),
    district_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS province_table (
    province_id INTEGER PRIMARY KEY,
    province_name VARCHAR(255) NOT NULL
);, parameters: None
[2024-02-01 16:15:30,698] {postgres.py:94} INFO - NOTICE:  relation "case_table" already exists, skipping

[2024-02-01 16:15:30,698] {postgres.py:94} INFO - NOTICE:  relation "district_table" already exists, skipping

[2024-02-01 16:15:30,698] {postgres.py:94} INFO - NOTICE:  relation "province_table" already exists, skipping

[2024-02-01 16:15:30,819] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_20, task_id=dim_postgres, execution_date=20240201T161523, start_date=20240201T161529, end_date=20240201T161530
[2024-02-01 16:15:30,887] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 16:15:31,154] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
