[2024-02-01 16:19:38,486] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_20.dim_postgres manual__2024-02-01T16:15:23.940128+00:00 [queued]>
[2024-02-01 16:19:38,500] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_20.dim_postgres manual__2024-02-01T16:15:23.940128+00:00 [queued]>
[2024-02-01 16:19:38,500] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 16:19:38,500] {taskinstance.py:1357} INFO - Starting attempt 2 of 3
[2024-02-01 16:19:38,501] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-01 16:19:38,526] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_postgres> on 2024-02-01 16:15:23.940128+00:00
[2024-02-01 16:19:38,532] {standard_task_runner.py:52} INFO - Started process 6972 to run task
[2024-02-01 16:19:38,537] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_20', 'dim_postgres', 'manual__2024-02-01T16:15:23.940128+00:00', '--job-id', '291', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp8kkxl__4', '--error-file', '/tmp/tmpa2y8z9qv']
[2024-02-01 16:19:38,537] {standard_task_runner.py:80} INFO - Job 291: Subtask dim_postgres
[2024-02-01 16:19:38,736] {task_command.py:369} INFO - Running <TaskInstance: project_6_20.dim_postgres manual__2024-02-01T16:15:23.940128+00:00 [running]> on host 1fafaef2f352
[2024-02-01 16:19:38,968] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_20
AIRFLOW_CTX_TASK_ID=dim_postgres
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T16:15:23.940128+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-02-01T16:15:23.940128+00:00
[2024-02-01 16:19:39,023] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-02-01 16:19:39,076] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS case_table (
    id INTEGER PRIMARY KEY,
    status_name VARCHAR(255) NOT NULL,
    status_detail VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS district_table (
    district_id INTEGER PRIMARY KEY,
    province_id INTEGER REFERENCES province_table(province_id),
    district_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS province_table (
    province_id INTEGER PRIMARY KEY,
    province_name VARCHAR(255) NOT NULL
);, parameters: None
[2024-02-01 16:19:39,083] {postgres.py:94} INFO - NOTICE:  relation "case_table" already exists, skipping

[2024-02-01 16:19:39,084] {postgres.py:94} INFO - NOTICE:  relation "district_table" already exists, skipping

[2024-02-01 16:19:39,084] {postgres.py:94} INFO - NOTICE:  relation "province_table" already exists, skipping

[2024-02-01 16:19:39,157] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_20, task_id=dim_postgres, execution_date=20240201T161523, start_date=20240201T161938, end_date=20240201T161939
[2024-02-01 16:19:39,196] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-01 16:19:39,363] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
