[2024-02-02 06:43:10,593] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_28.dim_postgres scheduled__2024-02-01T06:42:45.442031+00:00 [queued]>
[2024-02-02 06:43:10,608] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: project_6_28.dim_postgres scheduled__2024-02-01T06:42:45.442031+00:00 [queued]>
[2024-02-02 06:43:10,608] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2024-02-02 06:43:10,608] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2024-02-02 06:43:10,609] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2024-02-02 06:43:10,645] {taskinstance.py:1377} INFO - Executing <Task(PostgresOperator): dim_postgres> on 2024-02-01 06:42:45.442031+00:00
[2024-02-02 06:43:10,658] {standard_task_runner.py:52} INFO - Started process 5523 to run task
[2024-02-02 06:43:10,663] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'project_6_28', 'dim_postgres', 'scheduled__2024-02-01T06:42:45.442031+00:00', '--job-id', '441', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpys3tazpq', '--error-file', '/tmp/tmpzb25u8ck']
[2024-02-02 06:43:10,667] {standard_task_runner.py:80} INFO - Job 441: Subtask dim_postgres
[2024-02-02 06:43:10,885] {task_command.py:369} INFO - Running <TaskInstance: project_6_28.dim_postgres scheduled__2024-02-01T06:42:45.442031+00:00 [running]> on host 20775c919683
[2024-02-02 06:43:11,204] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=project_6_28
AIRFLOW_CTX_TASK_ID=dim_postgres
AIRFLOW_CTX_EXECUTION_DATE=2024-02-01T06:42:45.442031+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2024-02-01T06:42:45.442031+00:00
[2024-02-02 06:43:11,273] {base.py:68} INFO - Using connection ID 'postgres_dwh' for task execution.
[2024-02-02 06:43:11,318] {dbapi.py:208} INFO - Running statement: CREATE TABLE IF NOT EXISTS case_table (
    id INTEGER,
    status_name VARCHAR(255) NOT NULL,
    status_detail VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS province_table (
    province_id INTEGER PRIMARY KEY,
    province_name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS district_table (
    district_id INTEGER PRIMARY KEY,
    province_id INTEGER,
    district_name VARCHAR(255) NOT NULL
);
, parameters: None
[2024-02-02 06:43:11,325] {postgres.py:94} INFO - NOTICE:  relation "case_table" already exists, skipping

[2024-02-02 06:43:11,325] {postgres.py:94} INFO - NOTICE:  relation "province_table" already exists, skipping

[2024-02-02 06:43:11,326] {postgres.py:94} INFO - NOTICE:  relation "district_table" already exists, skipping

[2024-02-02 06:43:11,405] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=project_6_28, task_id=dim_postgres, execution_date=20240201T064245, start_date=20240202T064310, end_date=20240202T064311
[2024-02-02 06:43:11,446] {local_task_job.py:156} INFO - Task exited with return code 0
[2024-02-02 06:43:11,653] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
